In [ ]:
import torch
print(torch)
# import torch.nn as nn
# import numpy as np
# import matplotlib.pyplot as plt

<module 'torch' (namespace) from ['c:\\Users\\nakamura\\anaconda3\\envs\\practice\\Lib\\site-packages\\torch']>


In [ ]:
# x = torch.rand(5, 3)
# print(x)
# y = x.view(-1, 5)
# print(y)

# if torch.cuda.is_available():
#     device = torch.device("cuda")          # a CUDA device object
#     y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
#     x = x.to(device)                       # or just use strings ``.to("cuda")``
#     z = x + y
#     print(z)
#     print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


tensor([[0.8527, 0.0348, 0.2470],
        [0.7806, 0.7069, 0.0680],
        [0.9226, 0.0830, 0.8465],
        [0.8807, 0.2728, 0.3422],
        [0.3098, 0.9099, 0.7389]])
tensor([[0.8527, 0.0348, 0.2470, 0.7806, 0.7069],
        [0.0680, 0.9226, 0.0830, 0.8465, 0.8807],
        [0.2728, 0.3422, 0.3098, 0.9099, 0.7389]])
tensor([[1.8527, 1.0348, 1.2470],
        [1.7806, 1.7069, 1.0680],
        [1.9226, 1.0830, 1.8465],
        [1.8807, 1.2728, 1.3422],
        [1.3098, 1.9099, 1.7389]], device='cuda:0')
tensor([[1.8527, 1.0348, 1.2470],
        [1.7806, 1.7069, 1.0680],
        [1.9226, 1.0830, 1.8465],
        [1.8807, 1.2728, 1.3422],
        [1.3098, 1.9099, 1.7389]], dtype=torch.float64)
